"""Change Product

Revision ID: f5bf6c1be1c2
Revises: d1bdda22dc6a
Create Date: 2025-03-03 20:22:48.880856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5bf6c1be1c2'
down_revision: Union[str, None] = 'd1bdda22dc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('min_packing', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('image', sa.Text(), nullable=True))
    op.drop_column('products', 'hidden_content')
    op.drop_column('products', 'file_id')
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('purchases', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchases', 'quantity')
    op.add_column('products', sa.Column('file_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('hidden_content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('products', 'image')
    op.drop_column('products', 'min_packing')
    # ### end Alembic commands ###
